export type InitialCustomerData = {
	name: string
	internalCode: string
	amount: number
	direction: 'receivable' | 'payable' | 'zero'
	phone?: string
}

// Generated from دفتر الأستاذ الزبائن.xlsx.
export const INITIAL_CUSTOMERS_DATA: InitialCustomerData[] = [
	{
		name: 'حمودة مبسبس',
		internalCode: '002202',
		amount: 119.4,
		direction: 'receivable',
	},
	{
		name: 'سعيد الهلال / عموريا',
		internalCode: '121005',
		amount: 53.36,
		direction: 'receivable',
	},
	{
		name: 'ابو وضحه',
		internalCode: '121008',
		amount: 8.96,
		direction: 'receivable',
	},
	{
		name: 'ابو العبد الهيبي',
		internalCode: '121009',
		amount: 12.46,
		direction: 'receivable',
	},
	{
		name: 'فيصل البرهومي',
		internalCode: '121011',
		amount: 11.19,
		direction: 'receivable',
	},
	{
		name: 'محمد الفلاح / امير / كيا اخضر',
		internalCode: '121015',
		amount: 25.42,
		direction: 'receivable',
	},
	{
		name: 'الشلحاوي / ابو مالك',
		internalCode: '121016',
		amount: 69,
		direction: 'payable',
	},
	{
		name: 'ابو عيد السطوف',
		internalCode: '121017',
		amount: 20.9,
		direction: 'receivable',
	},
	{
		name: 'حسن سطوف',
		internalCode: '121018',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'هلال النابلسي',
		internalCode: '121021',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو ايهم الزوباني',
		internalCode: '121027',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'عصام الخروبي',
		internalCode: '121032',
		amount: 110.07,
		direction: 'receivable',
	},
	{
		name: 'راتب سليمان ابو عمر',
		internalCode: '121040',
		amount: 57.84,
		direction: 'receivable',
	},
	{
		name: 'ابو سامي .ابو شنب امير',
		internalCode: '121044',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'محمد العيسى البردان',
		internalCode: '121045',
		amount: 10.07,
		direction: 'receivable',
	},
	{
		name: 'ابو ابراهيم ابو حديد',
		internalCode: '121046',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'مهيب سيارة انتر 65',
		internalCode: '121050',
		amount: 23.13,
		direction: 'receivable',
	},
	{
		name: 'مصطفى النابلسي ابو البراء',
		internalCode: '121051',
		amount: 143.52,
		direction: 'receivable',
	},
	{
		name: 'ابو دعاس / فادي',
		internalCode: '121058',
		amount: 11.19,
		direction: 'receivable',
	},
	{
		name: 'حسن السعد',
		internalCode: '121066',
		amount: 2.99,
		direction: 'receivable',
	},
	{
		name: 'ابو راشد البردان',
		internalCode: '121069',
		amount: 96.27,
		direction: 'receivable',
	},
	{
		name: 'صياح الشامي / فادي',
		internalCode: '121074',
		amount: 37.29,
		direction: 'receivable',
	},
	{
		name: 'ابو فادي سابا مطعم',
		internalCode: '121075',
		amount: 17.54,
		direction: 'receivable',
	},
	{
		name: 'مدين الساعدي',
		internalCode: '121078',
		amount: 8.96,
		direction: 'receivable',
	},
	{
		name: 'قاسم كيزان',
		internalCode: '121085',
		amount: 14.55,
		direction: 'receivable',
	},
	{
		name: 'عمر ابو ليلى تل شهاب',
		internalCode: '121088',
		amount: 38,
		direction: 'receivable',
	},
	{
		name: 'ابو عبدو / دعاس / كيا قلاب',
		internalCode: '121091',
		amount: 95.54,
		direction: 'receivable',
	},
	{
		name: 'حمودة ابو حمدة',
		internalCode: '121093',
		amount: 14.93,
		direction: 'receivable',
	},
	{
		name: 'حسن نميري',
		internalCode: '121098',
		amount: 79.62,
		direction: 'receivable',
	},
	{
		name: 'ضياء شقران / تل شهاب',
		internalCode: '121101',
		amount: 144.78,
		direction: 'receivable',
	},
	{
		name: 'أبو خالد الربداوي / أمير',
		internalCode: '121102',
		amount: 2.24,
		direction: 'receivable',
	},
	{
		name: 'قاسم بردان / طفس',
		internalCode: '121105',
		amount: 330,
		direction: 'receivable',
	},
	{
		name: 'ياسين الجسيم / ابو همام مساكن جلين',
		internalCode: '121106',
		amount: 2.61,
		direction: 'receivable',
	},
	{
		name: 'ابو محمد الرفاعي / الجسيم',
		internalCode: '121107',
		amount: 15.95,
		direction: 'receivable',
	},
	{
		name: 'نادر عديسات',
		internalCode: '121112',
		amount: 14.93,
		direction: 'receivable',
	},
	{
		name: 'شادي هويمل',
		internalCode: '121114',
		amount: 42.91,
		direction: 'receivable',
	},
	{
		name: 'نضال عزوز',
		internalCode: '121117',
		amount: 27.24,
		direction: 'receivable',
	},
	{
		name: 'عمر بلاستيك',
		internalCode: '121120',
		amount: 18.66,
		direction: 'receivable',
	},
	{
		name: 'مهند هويمل',
		internalCode: '121126',
		amount: 72.39,
		direction: 'receivable',
	},
	{
		name: 'سرفيس جمعه',
		internalCode: '121132',
		amount: 74.63,
		direction: 'receivable',
	},
	{
		name: 'عامر الميكانيكي',
		internalCode: '121133',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ادهم العقرباوي ابو ميار',
		internalCode: '121135',
		amount: 22.39,
		direction: 'receivable',
	},
	{
		name: 'حسن المساكن',
		internalCode: '121136',
		amount: 22.39,
		direction: 'receivable',
	},
	{
		name: 'نصر الظاهر / الربايعة',
		internalCode: '121138',
		amount: 25,
		direction: 'receivable',
	},
	{
		name: 'عمر الادعس',
		internalCode: '121139',
		amount: 7.46,
		direction: 'receivable',
	},
	{
		name: 'احمد عبد العزيز / قيس',
		internalCode: '121144',
		amount: 79.25,
		direction: 'receivable',
	},
	{
		name: 'جهاد العوضي ابو احمد',
		internalCode: '121148',
		amount: 777.73,
		direction: 'receivable',
	},
	{
		name: 'مالك الحنيني ابو فيصل',
		internalCode: '121149',
		amount: 22.39,
		direction: 'receivable',
	},
	{
		name: 'ابو حسن سطوف',
		internalCode: '121156',
		amount: 23.51,
		direction: 'receivable',
	},
	{
		name: 'الحلاب الهاروني',
		internalCode: '121157',
		amount: 17.16,
		direction: 'receivable',
	},
	{
		name: 'رائد مصيبيح / قيس',
		internalCode: '121158',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'فؤاد الزوباني ابن عمي',
		internalCode: '121159',
		amount: 94.03,
		direction: 'receivable',
	},
	{
		name: 'نزار النابلسي',
		internalCode: '121164',
		amount: 7.09,
		direction: 'receivable',
	},
	{
		name: 'ابو حسين الساعدي',
		internalCode: '121177',
		amount: 11.94,
		direction: 'receivable',
	},
	{
		name: 'حمودة عطية / باقر',
		internalCode: '121183',
		amount: 13.81,
		direction: 'receivable',
	},
	{
		name: 'محمد الناطور ابو عايش / امير',
		internalCode: '121189',
		amount: 10.07,
		direction: 'receivable',
	},
	{
		name: 'ابو عبدالله الزعبي',
		internalCode: '121190',
		amount: 7.46,
		direction: 'receivable',
	},
	{
		name: 'ابو عمران مناجرة',
		internalCode: '121192',
		amount: 4.48,
		direction: 'receivable',
		phone: '0987143839',
	},
	{
		name: 'عبود الشامي عده',
		internalCode: '22113',
		amount: 48.51,
		direction: 'receivable',
	},
	{
		name: 'نورس كيوان / عامر',
		internalCode: '221143',
		amount: 150.39,
		direction: 'receivable',
	},
	{
		name: 'طارق الربداوي /',
		internalCode: '221147',
		amount: 8.21,
		direction: 'receivable',
		phone: '0935631759',
	},
	{
		name: 'رافت قيس',
		internalCode: '221150',
		amount: 0,
		direction: 'zero',
		phone: '0992092630',
	},
	{
		name: 'ابو مدين طربش',
		internalCode: '221152',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو حمزة الدبس / امير',
		internalCode: '221160',
		amount: 19.4,
		direction: 'receivable',
	},
	{
		name: 'معمر الميساوي',
		internalCode: '221161',
		amount: 24.25,
		direction: 'receivable',
	},
	{
		name: 'ابو ليث الطوبرجي',
		internalCode: '221173',
		amount: 17.16,
		direction: 'receivable',
	},
	{
		name: 'ابو رغيد طفس',
		internalCode: '221177',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'فادي الخالدي',
		internalCode: '221179',
		amount: 70.45,
		direction: 'receivable',
	},
	{
		name: 'محمد الغزاوي / المساكن',
		internalCode: '221180',
		amount: 25.37,
		direction: 'receivable',
	},
	{
		name: 'محمود الشمري',
		internalCode: '221181',
		amount: 13.9,
		direction: 'receivable',
	},
	{
		name: 'ابو خليل العبيلي',
		internalCode: '221182',
		amount: 33.58,
		direction: 'receivable',
	},
	{
		name: 'عزالدين الخالدي / قيس',
		internalCode: '221186',
		amount: 37.69,
		direction: 'receivable',
	},
	{
		name: 'ابو بلال عميش',
		internalCode: '221188',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'عبدو الحمصي',
		internalCode: '221192',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو وليد العقرباوي',
		internalCode: '221195',
		amount: 17.91,
		direction: 'receivable',
	},
	{
		name: 'ياسر العمقي',
		internalCode: '221196',
		amount: 13.43,
		direction: 'receivable',
	},
	{
		name: 'ابو فراس نصرالله',
		internalCode: '221206',
		amount: 8.96,
		direction: 'receivable',
	},
	{
		name: 'مصطفي ابو احمد / الشجرة',
		internalCode: '221207',
		amount: 703.4,
		direction: 'receivable',
	},
	{
		name: 'زياد السيطري',
		internalCode: '221210',
		amount: 32.09,
		direction: 'receivable',
	},
	{
		name: 'ايمن عطية ابو يزن',
		internalCode: '221212',
		amount: 161.19,
		direction: 'receivable',
	},
	{
		name: 'ابو خليل برمو مخرطة طفس',
		internalCode: '221214',
		amount: 175.89,
		direction: 'receivable',
	},
	{
		name: 'صلاح حريذين / امير',
		internalCode: '221215',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو صياح البرهومي',
		internalCode: '221219',
		amount: 109.29,
		direction: 'receivable',
	},
	{
		name: 'السيارة السوزي',
		internalCode: '221222',
		amount: 972.28,
		direction: 'receivable',
	},
	{
		name: 'هاني البكاري / / امير \\\\',
		internalCode: '221223',
		amount: 5.22,
		direction: 'receivable',
	},
	{
		name: 'صاحب ابو رغيد طفس',
		internalCode: '221224',
		amount: 42.91,
		direction: 'receivable',
	},
	{
		name: 'فؤاد الدبس',
		internalCode: '221226',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو يزن فرحان الزوباني',
		internalCode: '221227',
		amount: 54.85,
		direction: 'receivable',
	},
	{
		name: 'ابو زيد المحمدي سيارة ماء',
		internalCode: '221229',
		amount: 8.51,
		direction: 'receivable',
	},
	{
		name: 'ابو محمد مليحه',
		internalCode: '221230',
		amount: 54.48,
		direction: 'receivable',
	},
	{
		name: 'عبد الباسط الغادة',
		internalCode: '221231',
		amount: 20.15,
		direction: 'receivable',
	},
	{
		name: 'شادي الزوباني',
		internalCode: '221232',
		amount: 111.94,
		direction: 'receivable',
	},
	{
		name: 'يارا الهيسم',
		internalCode: '221233',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'نصر نجم / فادي',
		internalCode: '221234',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'مركز الزيتون',
		internalCode: '221235',
		amount: 1777.24,
		direction: 'receivable',
	},
	{
		name: 'مكب حريذين طفس',
		internalCode: '221236',
		amount: 12.31,
		direction: 'receivable',
	},
	{
		name: 'ابو خالد الحنيني',
		internalCode: '221238',
		amount: 85.82,
		direction: 'receivable',
	},
	{
		name: 'خالد الجمال',
		internalCode: '221239',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'زيد العوضي .ابو ايهم',
		internalCode: '221240',
		amount: 680,
		direction: 'receivable',
	},
	{
		name: 'عمر شحاده',
		internalCode: '221241',
		amount: 10.45,
		direction: 'receivable',
	},
	{
		name: 'امير ابو وائل الربداوي',
		internalCode: '221242',
		amount: 110.32,
		direction: 'receivable',
	},
	{
		name: 'شادي هويمل \\ دراسه \\',
		internalCode: '221243',
		amount: 22.39,
		direction: 'receivable',
	},
	{
		name: 'ثائر السيطري',
		internalCode: '221244',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ابو وليد مجبلي',
		internalCode: '221245',
		amount: 89.82,
		direction: 'receivable',
		phone: '0997970301',
	},
	{
		name: 'عبدالله الصالح',
		internalCode: '221246',
		amount: 0,
		direction: 'zero',
		phone: '0983227292',
	},
	{
		name: 'قاسم عذرا',
		internalCode: '221248',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'مجبلي / / اذاعة \\\\',
		internalCode: '221249',
		amount: 33.21,
		direction: 'receivable',
	},
	{
		name: 'ابو العبد الصبيحي الحلاب',
		internalCode: '221250',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'شادي هويمل \\ حصادة \\',
		internalCode: '221251',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'ليث نميري',
		internalCode: '221252',
		amount: 8.81,
		direction: 'receivable',
		phone: '0997778449',
	},
	{
		name: 'فرزات ابو طارق الميساوي',
		internalCode: '221253',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'امجد فجر.. امير',
		internalCode: '221254',
		amount: 0,
		direction: 'zero',
		phone: '0931458507',
	},
	{
		name: 'موسئ حميد اليادودة',
		internalCode: '221255',
		amount: 0,
		direction: 'zero',
		phone: '0934980307',
	},
	{
		name: 'بسام شحادة',
		internalCode: '221256',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'احمد مصيبيح .. امير',
		internalCode: '221257',
		amount: 37.21,
		direction: 'receivable',
	},
	{
		name: 'باص اخو ابو احمد الشجرة',
		internalCode: '221259',
		amount: 70.45,
		direction: 'receivable',
	},
	{
		name: 'عيد الديري كيا 4000',
		internalCode: '221260',
		amount: 35.82,
		direction: 'receivable',
	},
	{
		name: 'المركز ابوي ابو عايش 2026',
		internalCode: '221261',
		amount: 93.28,
		direction: 'receivable',
	},
	{
		name: 'ابو شادي جباوي',
		internalCode: '221262',
		amount: 139.13,
		direction: 'receivable',
	},
	{
		name: 'ماجد عزب',
		internalCode: '221263',
		amount: 0,
		direction: 'zero',
		phone: '0985443060',
	},
	{
		name: 'ابو البراء عميان',
		internalCode: '221264',
		amount: 35,
		direction: 'receivable',
	},
	{
		name: 'ابو عمران تسيل',
		internalCode: '221265',
		amount: 28.06,
		direction: 'payable',
	},
	{
		name: 'ابو حسين نصرالله',
		internalCode: '221266',
		amount: 40,
		direction: 'receivable',
	},
	{
		name: 'ابو وصفي الربداوي',
		internalCode: '221267',
		amount: 11.19,
		direction: 'receivable',
	},
	{
		name: 'مهند الجمال',
		internalCode: '221268',
		amount: 97.01,
		direction: 'receivable',
	},
	{
		name: 'حسن ذيبان',
		internalCode: '221269',
		amount: 0,
		direction: 'zero',
	},
	{
		name: 'محمود فرحان النابلسي',
		internalCode: '221270',
		amount: 86.19,
		direction: 'receivable',
	},
	{
		name: 'ابو عطا الزعبي',
		internalCode: '221271',
		amount: 7.46,
		direction: 'receivable',
	},
	{
		name: 'اسحاق وليد الغانم',
		internalCode: '221274',
		amount: 2000,
		direction: 'receivable',
	},
	{
		name: 'وائل السلام .. نوئ',
		internalCode: '221275',
		amount: 29.85,
		direction: 'receivable',
	},
	{
		name: 'عبد حريذين.. امير',
		internalCode: '221276',
		amount: 31.34,
		direction: 'receivable',
	},
	{
		name: 'ايمن عطية.. نسيبو ابراهيم',
		internalCode: '221278',
		amount: 309.7,
		direction: 'receivable',
	},
	{
		name: 'عبد ابو الذهب .. مزيريب',
		internalCode: '221279',
		amount: 168.66,
		direction: 'receivable',
	},
	{
		name: 'ابو سليمان باص طفس.. امير',
		internalCode: '221280',
		amount: 0,
		direction: 'zero',
	},
]
