export enum UserRole {
	SUPER_ADMIN = 'super_admin',
	OWNER = 'owner',
	ADMIN = 'admin',
	CASHIER = 'cashier',
	EMPLOYEE = 'employee',
}

export enum AllowedActions {
	// GENERAL
	ADD_PRODUCT = 'addProduct',
	EDIT_PRODUCT = 'editProduct',
	DELETE_PRODUCT = 'deleteProduct',
	ADD_REPORT = 'addReport',
	EDIT_REPORT = 'editReport',
	DELETE_REPORT = 'deleteReport',
}
export enum Breakpoints {
	MOBILE = 'mobile',
	TABLET = 'tablet',
	DESKTOP = 'desktop',
	LARGE_DESKTOP = 'large_desktop',
}

export enum ACTIVITY_TYPE {
	PRICE = 'PA',
	PROMOTIONS = 'PO',
	ALL_ACTIVITIES = 'ALL',
	SPACE_AND_LOCATION = 'SL',
	SPACE_AND_LOCATION_LOCATIONS = 'SL_LOCATIONS',
	SPACE_AND_LOCATION_SHOPS = 'SL_SHOPS',
	SPACE_AND_LOCATION_SHOP_DETAILS = 'SL_SHOP_DETAILS',
	SPACE_AND_LOCATION_TICKET_CANCELLATION = 'SL_TICKET_CANCELLATION',
	SPACE_AND_LOCATION_TICKET_ACQUISITION = 'SL_TICKET_ACQUISITION',
	SPACE_AND_LOCATION_SPACES = 'SL_SPACES',
	SPACE_AND_LOCATION_MEDIA_EXCHANGE = 'SL_MEDIA_EXCHANGE',
	COMPLAINTS = 'COMPLAINTS',
}
