export const SEE = {
	welcome: 'welcome',
	daily: 'daily',
	barcode: 'barcode',
	orders: 'orders',
	settings: 'settings',
	settingsProducts: 'settings.products',
	settingsLanguage: 'settings.language',
	settingsCurrencies: 'settings.currencies',
	settingsWorkMode: 'settings.workMode',
	settingsInvoice: 'settings.invoice',
	products: 'products',
	productsAdd: 'products.add',
	supplier: 'supplier',
	productsBuyingPrice: 'products.buyingPrice',
	productsWholesalePrice: 'products.wholesalePrice',
	productsSemiWholesalePrice: 'products.semiWholesalePrice',
	productsEdit: 'products.edit',
	productsDelete: 'products.delete',
	productsPrintBarcode: 'products.printBarcode',
	productsNotifications: 'products.notifications',
	customers: 'customers',
	customersAdd: 'customers.add',
	customersTotalReceivable: 'customers.totalReceivable',
	suppliersAdd: 'suppliers.add',
	suppliersTotalPayable: 'suppliers.totalPayable',
	invoices: 'invoices',
	invoicesBuyingAdd: 'invoices.buying.add',
	invoicesEntriesAdd: 'invoices.entries.add',
	sellingInvoices: 'sellingInvoices',
	sellingInvoicesBuyingButton: 'sellingInvoices.buyingButton',
	sellingInvoicesSellingButton: 'sellingInvoices.sellingButton',
	sellingInvoicesEntriesButton: 'sellingInvoices.entriesButton',
	sellingInvoicesSummary: 'sellingInvoices.summary',
	sellingInvoicesAiRead: 'sellingInvoices.aiRead',
	reports: 'reports',
	categories: 'categories',
	partners: 'partners',
	employees: 'employees',
	usersInvite: 'users.invite',
	usersList: 'users.list',
} as const

export type SeeId = (typeof SEE)[keyof typeof SEE]
