import { useMemo } from 'react'
import useAllowedActions from '../../../shared/hooks/useAllowedActions'
import { useSee } from '../../../shared/hooks/useSee'
import { SEE } from '../../../shared/seeFlags'
import { ColumnDef } from '../../list/columnConfig/layout'
import { PROMOTION_LIST_WIDTHS_MAP_IN_REM } from '../../list/shared/constants'
import { ProductSortHeaderKey } from '../../list/shared/globalEnums'

export const useProductColumnCatalog = (): ColumnDef[] => {
	const {
		seeSupplier,
		seeStockQuantity,
		seeMinStockQuantity,
		seeBuyCost,
		seeWholesalePrice,
		seeSemiWholesalePrice,
		seeDiscount,
		seeLocationWarehouse,
		seeLocationShelf,
	} = useAllowedActions()
	const { canSee } = useSee()
	const canSeeCategories = canSee(SEE.categories)

	return useMemo(
		() => [
			{
				id: 'NAME',
				labelKey: 'common.productName',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.NAME,
				locked: true,
				sortKey: ProductSortHeaderKey.NAME,
			},
			{
				id: 'LATIN_NAME',
				labelKey: 'productModal.latinName',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.LATIN_NAME,
				sortKey: ProductSortHeaderKey.LATIN_NAME,
				defaultHidden: true,
			},
			{
				id: 'BARCODE',
				labelKey: 'common.barcode',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.BARCODE,
				sortKey: ProductSortHeaderKey.BARCODE,
			},
			{
				id: 'CATEGORY_NAME',
				labelKey: 'common.category',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.CATEGORY_NAME,
				sortKey: ProductSortHeaderKey.CATEGORY_NAME,
				available: canSeeCategories,
			},
			{
				id: 'BRAND_NAME',
				labelKey: 'common.brand',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.BRAND,
				sortKey: ProductSortHeaderKey.BRAND_NAME,
				defaultHidden: true,
			},
			{
				id: 'SUPPLIER_NAME',
				labelKey: 'common.supplierName',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.SUPPLIER_NAME,
				sortKey: ProductSortHeaderKey.SUPPLIER_NAME,
				available: seeSupplier,
			},
			{
				id: 'STOCK_QUANTITY',
				labelKey: 'common.stockQuantity',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.STOCK_QUANTITY,
				sortKey: ProductSortHeaderKey.STOCK_QUANTITY,
				available: seeStockQuantity,
			},
			{
				id: 'UNIT_NAME',
				labelKey: 'common.unit',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.UNIT,
				sortKey: ProductSortHeaderKey.UNIT_NAME,
			},
			{
				id: 'STOCK_MIN_QUANTITY',
				labelKey: 'common.stockMinQuantity',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.STOCK_MIN_QUANTITY,
				sortKey: ProductSortHeaderKey.STOCK_MIN_QUANTITY,
				available: seeMinStockQuantity,
			},
			{
				id: 'PRICE_BUY',
				labelKey: 'common.buyCost',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.PRICE_BUY,
				sortKey: ProductSortHeaderKey.PRICE_BUY_COST,
				available: seeBuyCost,
			},
			{
				id: 'PRICE_SELL',
				labelKey: 'common.priceSell',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.PRICE_SELL,
				locked: true,
				sortKey: ProductSortHeaderKey.PRICE_SELL,
			},
			{
				id: 'WHOLESALE_PRICE',
				labelKey: 'productModal.wholesalePrice',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.WHOLESALE_PRICE,
				sortKey: ProductSortHeaderKey.PRICE_WHOLESALE,
				available: seeWholesalePrice,
				defaultHidden: true,
			},
			{
				id: 'SEMI_WHOLESALE_PRICE',
				labelKey: 'productModal.semiWholesalePrice',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.SEMI_WHOLESALE_PRICE,
				sortKey: ProductSortHeaderKey.PRICE_SEMI_WHOLESALE,
				available: seeSemiWholesalePrice,
				defaultHidden: true,
			},
			{
				id: 'CURRENCY',
				labelKey: 'common.currency',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.CURRENCY,
				sortKey: ProductSortHeaderKey.CURRENCY,
			},
			{
				id: 'DISCOUNT',
				labelKey: 'common.discount',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.DISCOUNT,
				sortKey: ProductSortHeaderKey.DISCOUNT,
				align: 'right',
				available: seeDiscount,
			},
			{
				id: 'TAX_RATE',
				labelKey: 'productModal.taxRate',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.TAX_RATE,
				sortKey: ProductSortHeaderKey.TAX_RATE,
				defaultHidden: true,
			},
			{
				id: 'INTERNAL_CODE',
				labelKey: 'productModal.internalCode',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.INTERNAL_CODE,
				sortKey: ProductSortHeaderKey.INTERNAL_CODE,
				defaultHidden: true,
			},
			{
				id: 'PRODUCT_FACTORY_CODE',
				labelKey: 'productModal.productFactoryCode',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.PRODUCT_FACTORY_CODE,
				sortKey: ProductSortHeaderKey.PRODUCT_FACTORY_CODE,
				defaultHidden: true,
			},
			{
				id: 'LOCATION_WAREHOUSE',
				labelKey: 'common.locationWarehouse',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.LOCATION_WAREHOUSE,
				sortKey: ProductSortHeaderKey.LOCATION_WAREHOUSE,
				available: seeLocationWarehouse,
				defaultHidden: true,
			},
			{
				id: 'LOCATION_SHELF',
				labelKey: 'common.locationShelf',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.LOCATION_SHELF,
				sortKey: ProductSortHeaderKey.LOCATION_SHELF,
				available: seeLocationShelf,
				defaultHidden: true,
			},
			{
				id: 'EXPIRY_DATE',
				labelKey: 'productModal.expiryDate',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.START_DATE,
				sortKey: ProductSortHeaderKey.EXPIRY_DATE,
				defaultHidden: true,
			},
			{
				id: 'STATUS',
				labelKey: 'common.status',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.STATUS,
				sortKey: ProductSortHeaderKey.STATUS,
				defaultHidden: true,
			},
			{
				id: 'DESCRIPTION',
				labelKey: 'productModal.description',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.DESCRIPTION,
				sortKey: ProductSortHeaderKey.DESCRIPTION,
				defaultHidden: true,
			},
			{
				id: 'COLOR',
				labelKey: 'common.color',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.COLOR,
				sortKey: ProductSortHeaderKey.COLOR,
				defaultHidden: true,
			},
			{
				id: 'SIZE',
				labelKey: 'productModal.size',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.SIZE,
				sortKey: ProductSortHeaderKey.SIZE,
				defaultHidden: true,
			},
			{
				id: 'WEIGHT',
				labelKey: 'common.weight',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.WEIGHT,
				sortKey: ProductSortHeaderKey.WEIGHT,
				defaultHidden: true,
			},
			{
				id: 'LENGTH',
				labelKey: 'productModal.length',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.LENGTH,
				sortKey: ProductSortHeaderKey.LENGTH,
				defaultHidden: true,
			},
			{
				id: 'WIDTH',
				labelKey: 'productModal.width',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.WIDTH,
				sortKey: ProductSortHeaderKey.WIDTH,
				defaultHidden: true,
			},
			{
				id: 'HEIGHT',
				labelKey: 'productModal.height',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.HEIGHT,
				sortKey: ProductSortHeaderKey.HEIGHT,
				defaultHidden: true,
			},
			{
				id: 'FLAVOR',
				labelKey: 'productModal.flavor',
				width: PROMOTION_LIST_WIDTHS_MAP_IN_REM.FLAVOR,
				sortKey: ProductSortHeaderKey.FLAVOR,
				defaultHidden: true,
			},
		],
		[
			seeBuyCost,
			seeDiscount,
			seeLocationShelf,
			seeLocationWarehouse,
			seeMinStockQuantity,
			seeSemiWholesalePrice,
			seeStockQuantity,
			seeSupplier,
			seeWholesalePrice,
			canSeeCategories,
		],
	)
}
