export const BASE_ENDPOINT = '/api'
export const COLLECTION_NAMES = {
	PRODUCTS: 'products',
	CATEGORIES: 'categories',
	ORDERS: 'orders',
	INVOICES: 'invoices',
	USERS: 'users',
	INVENTORY: 'inventory',
	REPORTS: 'reports',
	DAILY_ACTIONS: 'dailyActions',
	TENANTS: 'tenants',
	SUPPLIERS: 'suppliers',
	CUSTOMERS: 'customers',
	EXPENSES: 'expenses',
	CURRENCIES: 'currencies',
	UNITS: 'units',
	PARTNERS: 'partners',
	BRANDS: 'brands',
	SHELVES: 'shelves',
	WAREHOUSES: 'warehouses',
	STOCK_MOVINGS: 'stockMovings',
} as const
