export const PROMOTION_LIST_WIDTHS_MAP_IN_REM = {
	CHECKBOX: 2,
	TICKET_TYPE: 5,
	SALES_AREA: 5,
	LOCATION: 6,
	TIME_FRAME: 7,
	SHOP: 8,
	SUPPLIER: 8,
	PREFERRED_BRAND: 8,
	FOCUS: 8,
	PLACEMENT_FEE: 8,
	PROMOTER_FEE: 8,
	PROMOTER_PER_DAY: 6.5,
	STICKY_RIGHT: 15,
} as const
export const LIST_INTERNAL_ONLY_COLUMNS: string[] = [
	'SUPPLIER',
	'COMBINED_TARGET_CONTRIBUTIONS',
	'LISTING',
]
