export const PROMOTION_LIST_WIDTHS_MAP_IN_REM = {
	CHECKBOX: 2,
	NAME: 5,
	BARCODE: 5,
	BRAND: 6,
	CATEGORY_NAME: 7,
	PRICE_BUY: 8,
	PRICE_SELL: 8,
	STOCK_QUANTITY: 8,
	SUPPLIER_NAME: 8,
	LOCATION_WAREHOUSE: 8,
	LOCATION_SHELF: 8,
	START_DATE: 6.5,
	STATUS: 5,
	STICKY_RIGHT: 15,
} as const
export const LIST_INTERNAL_ONLY_COLUMNS: string[] = [
	'SUPPLIER',
	'COMBINED_TARGET_CONTRIBUTIONS',
	'LISTING',
]
